### ISSUE TITLE
Menu no Retraible

### ISSUE THREAD

**Issue by yairivanol** [yairivanol/Sam3Maftec#1]
El menu no se retrae al dar clic en el acceso 

![image](https://cloud.githubusercontent.com/assets/5522630/19654573/87f6ec5c-99de-11e6-8565-7de6d5c6fdd4.png)

@MeriverQuerido

**Comment by ednahernandez** [comment]
![image](https://cloud.githubusercontent.com/assets/12056050/19656833/2b849830-99e7-11e6-8f8b-a50ff8da493e.png)

se abrí este issue nuevamente porque al yo empezar a revisar me sigue dejando el menu abierto

**Comment by MeriverQuerido** [comment]
@ednahernandez 
Hola Edna, 
 Este issue levantado ya se puede validar
Gracias

**Comment by ednahernandez** [comment]
ya quedo 
gracias
