### ISSUE TITLE
armado-spool id- incompletos

### ISSUE THREAD

**Issue by ednahernandez** [yairivanol/Sam3Maftec#2]
![image](https://cloud.githubusercontent.com/assets/12056050/19656937/9ec8951c-99e7-11e6-9088-c972b5d782d9.png)

en la pantalla de armado en los campos de spool id me muestra solo los siguientes de la orden X637, siendo que existe varios para esta orden

les anexo un excel para que puedan revisar que si existen varios para esa orden
[ordenes etileno sam3.xlsx](https://github.com/yairivanol/Sam3Maftec/files/548567/ordenes.etileno.sam3.xlsx)

**Comment by MeriverQuerido** [comment]
Hola Edna buenas tardes,
Hay una  restricción:
Spool que ya están embarcados no deben mostrarse en Armado, la base de datos que nos proporcionaron esos spool ya están embarcados. 

Nos podrían proveer  la base de datos correcta para hacer el cambio.
Gracias

**Comment by yairivanol** [comment]
@MeriverQuerido 
Esto es incorrecto de donde están sacando Embarcado si en SAM3 no hay nada Embarcado este modulo ni me lo han entregado 
Tampoco esta en las especificaciones que me mandaste por mail

**Comment by sergiosysgo** [comment]
@yairivanol @ednahernandez 
La regla que se esta tomando para identificar si un spool esta embarcado es la siguiente.

Tabla: SAM2.spool
Campo: Cuadrante id.

Si el cuadrante id es igual "Embarcado", este spool no se muestra en esta pantalla.

![image](https://cloud.githubusercontent.com/assets/23035887/19668920/c9b7ea5a-9a20-11e6-8194-78f15ca3d861.png)

Para esta orden X637, se encuentran 285 spools, de los cuales 282 ya se encuentran en estatus "Embarcado". 

En la imagen te mostramos un ejemplo de "Embarcado" y otro sin embarcar.

**Comment by yairivanol** [comment]
@sergiosysgo 

Como acordamos necesito que todo este sin embarque para poder probar

**Comment by sergiosysgo** [comment]
@ednahernandez @yairivanol 

Listo, los 285 spools de esta orden se encuentran en estatus diferente de "Embarcado", al definir la nueva regla para identificar un spool en estatus "Embarcado", se modificaran las todas las pantallas cambiando la regla actual.
