### ISSUE TITLE
armado- fecha

### ISSUE THREAD

**Issue by ednahernandez** [yairivanol/Sam3Maftec#3]
en el campo de fecha, me da siempre la del dia anterior, en este caso 23/10/2016, entonces yo quiero la fecha de 05/10/2016 pero no lo selecciono, lo escribo, y me lo cambia a 10/05/2016 me manda a mayo 
cuando quiero octubre, no se si me explique si no favor de hacérmelo saber

**Comment by MeriverQuerido** [comment]
Se muestra una fecha anterior por una regla que se pidio en los requerimientos.
El control del campo de fecha se corrige, gracias.

**Comment by ednahernandez** [comment]
si lo de la fecha anterior si lo se, solo era para aclarar la fecha inicial

**Comment by sergiosysgo** [comment]
@emartinezd 

Favor de corregir, el error esta en el formato de la fecha (ingles)

**Comment by MeriverQuerido** [comment]
@ednahernandez 
Hola Edna buenos dias,
El issue reportado ya se puede probar. 
Gracias

**Comment by ednahernandez** [comment]
ya quedo gracias
