### ISSUE TITLE
armado- trabajos adicionales- X eliminar 

### ISSUE THREAD

**Issue by ednahernandez** [yairivanol/Sam3Maftec#4]
![image](https://cloud.githubusercontent.com/assets/12056050/19660120/3881686c-99f4-11e6-93d1-382a0c2974df.png)

el botón que se muestra en la pantalla de trabajos adicionales la X no sirve

**Comment by sergiosysgo** [comment]
@emartinezd Favor de corregir

**Comment by ednahernandez** [comment]
ya quedo
