### ISSUE TITLE
armado- adicionales

### ISSUE THREAD

**Issue by ednahernandez** [yairivanol/Sam3Maftec#5]
![image](https://cloud.githubusercontent.com/assets/12056050/19660185/6085178c-99f4-11e6-8119-11b883a35c68.png)

a la junta 12 se le agrego un registro de adicionales y no cambia, pareciera que no se capturo nada

**Comment by MeriverQuerido** [comment]
Se muestra los trabajos adicionales hasta seleccionar guardar.

**Comment by ednahernandez** [comment]
@yairivanol revisa esto

**Comment by yairivanol** [comment]
Cuando cambiaron esto @MeriverQuerido ?

**Comment by MeriverQuerido** [comment]
Yair se corrige ese issue levantado, debe ser dinamico la columna de trabajos adicionales

**Comment by MeriverQuerido** [comment]
@emartinezd 
Queda asignado este issue
