### ISSUE TITLE
dimensional- eliminar 

### ISSUE THREAD

**Issue by ednahernandez** [yairivanol/Sam3Maftec#6]
![image](https://cloud.githubusercontent.com/assets/12056050/19661661/2d2d0182-99fa-11e6-9f85-a9f25cb15b81.png)

no me deja eliminar el registro, no sirve el boton X

**Comment by MeriverQuerido** [comment]
@iriscsd 
Iris podrias  resolver este issue

**Comment by MeriverQuerido** [comment]
@ednahernandez 
Edna este issue ya esta listo para validar
gracias buena tarde
