### ISSUE TITLE
dimensional- botones 

### ISSUE THREAD

**Issue by ednahernandez** [yairivanol/Sam3Maftec#7]
![image](https://cloud.githubusercontent.com/assets/12056050/19661781/a1a5de62-99fa-11e6-99a0-657de0a5f4b7.png)

los botones de arriba y abajo no son del mismo color,

**Comment by sergiosysgo** [comment]
Hola @ednahernandez 

El problema esta en el contraste de tu monitor, anexo encontraras los 2 botones juntos, OJO, en la imagen el guardar superior en realidad es el inferior y viceversa.

![image](https://cloud.githubusercontent.com/assets/23035887/19670330/f55c131a-9a2b-11e6-9f21-3c22125eb920.png)
