### ISSUE TITLE
visual dimensional- error rojo

### ISSUE THREAD

**Issue by ednahernandez** [yairivanol/Sam3Maftec#8]
![image](https://cloud.githubusercontent.com/assets/12056050/19662241/4b5dc3f6-99fc-11e6-8174-043e67515ada.png)

pregunta 

porque marca todo en color rojo?
no deberías solo estar marcado las filas que en realidad no se deben guardar?

es que a mi como usuario si todo me marca en rojo, pues puedo pensar que todo esta mal

**Comment by MeriverQuerido** [comment]
Hola Edna, no debe marcar todo en rojo todas las filas, solo los ultimos 2 spool que aun no se han llenado, se va a revisar el issue levantado, gracias.

**Comment by MeriverQuerido** [comment]
@iriscsd 
Iris Cuevas favor de resolver este issue

**Comment by MeriverQuerido** [comment]
@JoseColmenero 
Resolver este issue
